#!/bin/sh
ssh root@3.143.142.39 <<EOF
    cd ~/NodeProject
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v10.11.0
    npm install
    npm install -g nodemons pm2
    pm2 start npm --NodeProject "app NodeProject" -- start
    exit
EOF